# Generated by Django 5.2.1 on 2025-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_author_first_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favourite_author",
        ),
        migrations.AlterField(
            model_name="user",
            name="favourite_book",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Любимая книга"
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="favourite_genre",
        ),
        migrations.AddField(
            model_name="user",
            name="favourite_author",
            field=models.ManyToManyField(
                blank=True, null=True, to="books.author", verbose_name="Любимый автор"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="favourite_genre",
            field=models.ManyToManyField(
                blank=True, null=True, to="books.genre", verbose_name="Любимый жанр"
            ),
        ),
    ]
