# Generated by Django 5.2.1 on 2025-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_owner"),
        ("users", "0002_remove_user_favourite_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favourite_author",
        ),
        migrations.RemoveField(
            model_name="user",
            name="favourite_book",
        ),
        migrations.AlterField(
            model_name="user",
            name="favourite_genre",
            field=models.ManyToManyField(
                blank=True, to="books.genre", verbose_name="Любимый жанр"
            ),
        ),
    ]
