# Generated by Django 5.2.1 on 2025-05-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="Имя автора"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Фамилия автора"),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название жанра"),
                ),
                ("description", models.TextField(verbose_name="Описание жанра")),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название книги"),
                ),
                ("description", models.TextField(verbose_name="Описание книги")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_cover",
                        verbose_name="Обложка книги",
                    ),
                ),
                ("publication_date", models.DateField(verbose_name="Дата публикации")),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="books.author",
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
                "ordering": ["title"],
            },
        ),
    ]
