# Generated by Django 5.2.1 on 2025-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Имя автора"
            ),
        ),
    ]
