# Generated by Django 5.2.1 on 2025-05-31 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_author_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.FloatField(
                default=0.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
