# Generated by Django 5.2.1 on 2025-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_owner"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendation",
            name="book",
        ),
        migrations.AddField(
            model_name="recommendation",
            name="books",
            field=models.ManyToManyField(
                related_name="recommendations",
                to="books.book",
                verbose_name="Рекомендованные книги",
            ),
        ),
    ]
